import {
  Box,
  Container,
  Heading,
  Text,
  VStack,
  UnorderedList,
  ListItem,
  Link,
  Divider
} from '@chakra-ui/react';
import { useLocale } from '../lib/useLocale';
import SEOHead from '../components/SEOHead';

export default function PrivacyPolicy() {
  const { locale, t } = useLocale();

  return (
    <>
      <SEOHead 
        title={locale === 'zh' ? '隐私政策 - 吾今有世家修改器' : 'Privacy Policy - House of Legacy Editor'}
        description={locale === 'zh' ? '查看吾今有世家修改器的隐私政策和数据使用条款' : 'View the privacy policy and data usage terms for House of Legacy Editor'}
      />
      
      <Container maxW="4xl" py={8} pb={20}>
        <VStack spacing={6} align="stretch">
          <Heading as="h1" size="xl" textAlign="center">
            Privacy Policy
          </Heading>
          
          <Text fontSize="sm" color="gray.600" textAlign="center">
            Last updated: May 27, 2025
          </Text>

          <Divider />

          <Text>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </Text>

          <Text>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the{' '}
            <Link href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" isExternal color="blue.500">
              Free Privacy Policy Generator
            </Link>.
          </Text>

          <Heading as="h2" size="lg" mt={8}>
            Interpretation and Definitions
          </Heading>

          <Heading as="h3" size="md">
            Interpretation
          </Heading>
          <Text>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </Text>

          <Heading as="h3" size="md">
            Definitions
          </Heading>
          <Text>For the purposes of this Privacy Policy:</Text>

          <UnorderedList spacing={3} pl={4}>
            <ListItem>
              <Text><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to house of legacy cheat editor.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Country</strong> refers to: China</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Service</strong> refers to the Website.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
            </ListItem>
            <ListItem>
              <Text><strong>Website</strong> refers to house of legacy cheat editor, accessible from{' '}
                <Link href="https://savefile.space" isExternal color="blue.500">
                  savefile.space
                </Link>
              </Text>
            </ListItem>
            <ListItem>
              <Text><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
            </ListItem>
          </UnorderedList>

          <Heading as="h2" size="lg" mt={8}>
            Collecting and Using Your Personal Data
          </Heading>

          <Heading as="h3" size="md">
            Types of Data Collected
          </Heading>

          <Heading as="h4" size="sm">
            Personal Data
          </Heading>
          <Text>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </Text>
          <UnorderedList>
            <ListItem>Usage Data</ListItem>
          </UnorderedList>

          <Heading as="h4" size="sm">
            Usage Data
          </Heading>
          <Text>Usage Data is collected automatically when using the Service.</Text>
          <Text>
            Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </Text>

          <Heading as="h3" size="md" mt={6}>
            Use of Your Personal Data
          </Heading>
          <Text>The Company may use Personal Data for the following purposes:</Text>

          <UnorderedList spacing={3} pl={4}>
            <ListItem>
              <Text><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>To contact You:</strong> To contact You by email regarding updates or informative communications related to the functionalities, products or contracted services.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</Text>
            </ListItem>
            <ListItem>
              <Text><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</Text>
            </ListItem>
          </UnorderedList>

          <Heading as="h3" size="md" mt={6}>
            Security of Your Personal Data
          </Heading>
          <Text>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </Text>

          <Heading as="h2" size="lg" mt={8}>
            Children&apos;s Privacy
          </Heading>
          <Text>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
          </Text>

          <Heading as="h2" size="lg" mt={8}>
            Changes to this Privacy Policy
          </Heading>
          <Text>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </Text>

          <Heading as="h2" size="lg" mt={8}>
            Contact Us
          </Heading>
          <Text>If you have any questions about this Privacy Policy, You can contact us:</Text>
          <UnorderedList>
            <ListItem>
              By email:{' '}
              <Link href="mailto:clarezhangstr@gmail.com" color="blue.500">
                clarezhangstr@gmail.com
              </Link>
            </ListItem>
          </UnorderedList>
        </VStack>
      </Container>
    </>
  );
} 